service: serverless-microservice-bootstrap

provider:
  name: aws
  runtime: dotnetcore1.0

# you can overwrite defaults here
  stage: v1
  region: ap-southeast-2
  deploymentBucket: serverless-microservice-bootstrap.${self:provider.region}.deploys

# you can add packaging information here
package:
  artifact: src/Handlers/bin/release/netcoreapp1.0/publish/deploy-package.zip

functions:
  hello:
    handler: Handlers::Serverless.Dotnet.Handlers.Handler::Hello

  healthcheck:
    handler: Handlers::Serverless.Dotnet.Handlers.Handler::HealthCheck
    events:
      - http:
          path: healthcheck
          method: get
          cors: true  
